//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Passwords struct {
	ID        int32 `sql:"primary_key"`
	Userid    int32
	Password  string
	CreatedAt *time.Time
}
